# Terminal
bind=SUPER,t,spawn,kitty

# Noctalia
bind=SUPER,c,spawn,noctalia msg control-center toggle
bind=SUPER,Escape,spawn,noctalia msg session toggle

# Screenshot
bind=SHIFT+Print,spawn,sh -c 'grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%F_%H-%M-%S).png'

# Exit Mango
bind=SUPER,m,quit

# Workspaces
bind=SUPER,1,comboview,1
bind=SUPER,2,comboview,2
bind=SUPER,3,comboview,3
bind=SUPER,4,comboview,4

# Window Management
bind=SUPER,q,killclient
bind=SUPER+SHIFT,r,reload_config

# Layout
bind=ALT,t,setlayout,tile
bind=ALT,v,setlayout,vertical_grid
bind=ALT,c,setlayout,spiral
bind=ALT,x,setlayout,scroller
bind=ALT,n,switch_layout
bind=ALT,a,togglegaps

# Fullscreen & Floating
bind=SUPER,f,togglemaximizescreen
bind=SUPER+SHIFT,f,togglefullscreen
bind=ALT,f,togglefloating,

# Master Count
bind=SUPER,i,incnmaster,+1
bind=SUPER,p,incnmaster,-1

# Focus Window
bind=SUPER,left,focusdir,left
bind=SUPER,down,focusdir,down
bind=SUPER,up,focusdir,up
bind=SUPER,right,focusdir,right

# Move Window
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right

# Smart Move
bind=CTRL+SHIFT,h,smartmovewin,left
bind=CTRL+SHIFT,j,smartmovewin,down
bind=CTRL+SHIFT,k,smartmovewin,up
bind=CTRL+SHIFT,l,smartmovewin,right

# Mouse
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Gesture
gesturebind=none,left,3,focusdir,right
gesturebind=none,right,3,focusdir,left
gesturebind=none,up,3,viewtoright_have_client
gesturebind=none,down,3,viewtoleft_have_client
gesturebind=none,left,4,viewtoleft_have_client
gesturebind=none,right,4,viewtoright_have_client
gesturebind=none,up,4,toggleoverview
gesturebind=none,down,4,toggleoverview

bind=SUPER,0,toggleoverview
bind=SUPER+SHIFT,p,spawn,~/.config/mango/scripts/toggle-monitor.sh

# General
animations=1
gappih=5
gappiv=5
gappoh=5
gappov=5
borderpx=0
no_border_when_single=1
focuscolor=0x444444ff

repeat_rate=35
repeat_delay=200

# Custom Apps
bind=SUPER,e,spawn,nemo
bind=SUPER,w,spawn,zen-beta
bind=SUPER+SHIFT,w,spawn,helium
bind=CTRL+SHIFT,Escape,spawn,kitty -e btop

# Launcher
bind=SUPER,d,spawn,walker
